services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tripmate_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - AVIATIONSTACK_API_KEY=${AVIATIONSTACK_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres_pass@postgres_db:5432/tripmate_db
      - REDIS_URL=redis://redis_cache:6379/0
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy

  postgres_db:
    image: postgres:15-alpine
    container_name: tripmate_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=tripmate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tripmate_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:7-alpine
    container_name: tripmate_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
