"""
Structured Agent Data Schemas & Evidence Specifications

This module defines Pydantic schemas for:
- Evidence tracking and confidence verification
- Standardized structured agent output containers
- Dynamic planner Task DAG specifications
- Critic / Validator evaluation reports
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EvidenceType(str, Enum):
    API = "api"
    WEB_SEARCH = "web_search"
    LLM_ESTIMATE = "llm_estimate"
    FALLBACK = "fallback"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    ESTIMATED = "ESTIMATED"
    UNCERTAIN = "UNCERTAIN"
    UNAVAILABLE = "UNAVAILABLE"


class EvidenceItem(BaseModel):
    """Represents a piece of evidence supporting an agent's findings."""
    source_name: str = Field(description="Name of service or data source")
    source_type: EvidenceType = Field(default=EvidenceType.LLM_ESTIMATE)
    status: VerificationStatus = Field(default=VerificationStatus.ESTIMATED)
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    details: Optional[str] = Field(default=None)


class StructuredAgentOutput(BaseModel):
    """Standardized result schema returned by all specialist agents."""
    agent_name: str = Field(description="Unique agent identifier")
    status: str = Field(default="success", description="Status: success, degraded, or failed")
    result: Any = Field(description="Primary structured result or text output")
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    sources: List[EvidenceItem] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    execution_time_ms: float = Field(default=0.0)


class TaskSpec(BaseModel):
    """Specification for a single task within a dynamic plan DAG."""
    task_id: str = Field(description="Unique task identifier, e.g. flight_search")
    agent: str = Field(description="Target registered agent name")
    depends_on: List[str] = Field(default_factory=list, description="IDs of tasks that must execute before this task")
    priority: str = Field(default="medium", description="Priority level: low, medium, high")
    retry_limit: int = Field(default=2, ge=0, le=5)
    risk_level: str = Field(default="low", description="Risk level: low, medium, high")
    input_params: Dict[str, Any] = Field(default_factory=dict)


class PlanDAG(BaseModel):
    """Complete dynamically planned task graph."""
    tasks: List[TaskSpec] = Field(default_factory=list)
    reasoning: str = Field(default="")
    trip_constraints: Dict[str, Any] = Field(default_factory=dict)


class CriticReport(BaseModel):
    """Validation report generated by the Critic agent."""
    is_valid: bool = Field(description="Whether the current output plan meets all constraints")
    score: float = Field(default=1.0, ge=0.0, le=1.0, description="Overall quality/validity score")
    violations: List[str] = Field(default_factory=list, description="List of rule/constraint violations")
    recommendations: List[str] = Field(default_factory=list, description="Actionable improvement suggestions")
    requires_retry: bool = Field(default=False, description="Whether specific agent tasks should be re-executed")
    retry_tasks: List[str] = Field(default_factory=list, description="List of task IDs or agent names requiring retry")
